## Simulate the learning prcocess from study data

In [1]:
## Setup
import sqlite3
from typing import List, Dict
import os, sys
import dill as pickle
from pathlib import Path
from datetime import datetime
import ast
import copy



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy import array
import seaborn as sns

import logging
logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger()


# Add the directory where 'app/' lives to sys.path
root_path = Path.cwd().resolve()
if str(root_path) not in sys.path:
    sys.path.insert(0, str(root_path))

logger.info(f"Added to sys.path:  {root_path}")
logger.info(f"sys.path[-1]: {sys.path[-1]}")

try:
    from app.group_teaching.codes.simple_rl.utils import mdp_helpers
    from app.group_teaching.codes.simple_rl.planning import ValueIteration
    from app.group_teaching.codes.simple_rl.utils.make_mdp import make_custom_mdp
    from app.group_teaching.codes.policy_summarization.BEC_helpers import calc_solid_angles
    
    from app.group_teaching.codes.policy_summarization.BEC_helpers import remove_redundant_constraints, update_variable_filter, sample_human_models_uniform
    from app.group_teaching.codes.params_utils import get_mdp_parameters
    from app.group_teaching.codes.teams import particle_filter_team as pf_team

    
    logger.info("Imported simple_rl successfully")
except Exception as e:
    logger.info(f"Failed to import simple_rl: {e}")

logger.info(f"Functions in mdp_helpers: {dir(mdp_helpers)}")


Added to sys.path:  /home/sureshkj/Projects/flask_closed_loop_teaching/simple_game_test
sys.path[-1]: /home/sureshkj/.ipython


Loaded packages....
Db, migrate, login initialized....
Socketio initialized....
Models loaded....
Routes: Loaded flask apps...
Routes: Loaded "App"...
Routes: Loaded python apps...


/home/sureshkj/anaconda3/envs/aug_taxi/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:246: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),


Routes: Loaded group teaching apps...
Global db lock:  <unlocked _thread.lock object at 0x7aa7ecc95960>
Routes loaded....
Migrate initialized....
Login initialized....
Using 24 processes
Lock initialized....
Conditions initialized....
Groups initialized....
Db committed....
Imported simple_rl successfully
Functions in mdp_helpers: ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'colored', 'np', 'rollout_policy', 'rollout_policy_recursive']
Processing file: output_full_data_06_25.xlsx
File suffix: full_data_06_25.xlsx
Processing file: output_full_data_06_25.xlsx
File suffix: full_data_06_25.xlsx
Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
Parsing all data from Excel sheets...
Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_2

10840
Simulating learning for user:
652
Empty DataFrame
Columns: [id, timestamp, user_id, group_code, duration_ms, domain, interaction_type, group, round, iteration, subiteration, likert, moves, coordinates, is_opt_response, mdp_parameters, human_model, is_first_time, num_visits, engagement_short_answer, improvement_short_answer, final_score, all_scores, group_id]
Index: []

[0 rows x 24 columns]
Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
Parsing all data from Excel sheets...
['sb' 'at']
['652' '622' '642' '672' '632' '612' '1022' '1032' '1012' '1052' '1062'
 '1072' '1082' '1112' '1092' '1132' '1142' '1172' '1152' '1162' '1212'
 '1222' '1232' '1272' '1262' '1252' '1332' '1302' '1292' '1662' '1632'
 '1642' '1702' '1692' '1652' '1712' '1722' '1672' '1802' '1782' '1812'
 '1772' '1792' '1822' '1842' '1852' '1832' '2722' '2702' '271

Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
Parsing all data from Excel sheets...
['sb' 'at']
['652' '622' '642' '672' '632' '612' '1022' '1032' '1012' '1052' '1062'
 '1072' '1082' '1112' '1092' '1132' '1142' '1172' '1152' '1162' '1212'
 '1222' '1232' '1272' '1262' '1252' '1332' '1302' '1292' '1662' '1632'
 '1642' '1702' '1692' '1652' '1712' '1722' '1672' '1802' '1782' '1812'
 '1772' '1792' '1822' '1842' '1852' '1832' '2722' '2702' '2712' '2752'
 '2742' '2732' '2802' '2792' '2812' '2842' '2852' '2832' '2912' '2902'
 '2932' '2942' '2952' '2922' '3802' '3812' '3782' '3872' '3852' '3832'
 '3862' '3882' '3842' '3892' '3932' '3912' '3972' '3942' '3952' '3982'
 '3992' '3962' '4042' '4032' '4002' '4112' '4092' '4082' '4122' '4152'
 '4132' '891' '911' '901' '991' '1001' '981' '1011' '1021' '1031' '1111'
 '1091' '1141' '1051' '1101' '113

Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
Parsing all data from Excel sheets...
['sb' 'at']
['652' '622' '642' '672' '632' '612' '1022' '1032' '1012' '1052' '1062'
 '1072' '1082' '1112' '1092' '1132' '1142' '1172' '1152' '1162' '1212'
 '1222' '1232' '1272' '1262' '1252' '1332' '1302' '1292' '1662' '1632'
 '1642' '1702' '1692' '1652' '1712' '1722' '1672' '1802' '1782' '1812'
 '1772' '1792' '1822' '1842' '1852' '1832' '2722' '2702' '2712' '2752'
 '2742' '2732' '2802' '2792' '2812' '2842' '2852' '2832' '2912' '2902'
 '2932' '2942' '2952' '2922' '3802' '3812' '3782' '3872' '3852' '3832'
 '3862' '3882' '3842' '3892' '3932' '3912' '3972' '3942' '3952' '3982'
 '3992' '3962' '4042' '4032' '4002' '4112' '4092' '4082' '4122' '4152'
 '4132' '891' '911' '901' '991' '1001' '981' '1011' '1021' '1031' '1111'
 '1091' '1141' '1051' '1101' '113

10840
Simulating learning for user:
652
domain:
at
N trials:
0
Simulating learning for user:
652
domain:
sb
N trials:
26
N demos:
2
N tests:
2
id                                                                        256
timestamp                                          2025-04-23 20:50:34.941792
user_id                                                                   652
group_code                                                                  2
duration_ms                                                            3273.0
domain                                                                     sb
interaction_type                                                         demo
group                                                                     202
round                                                                       1
iteration                                                                   1
subiteration                                                              NaN

Simulating learning for user:
652
domain:
sb
N trials:
26
N demos:
2
N tests:
2
Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
Parsing all data from Excel sheets...
['sb' 'at']
['652' '622' '642' '672' '632' '612' '1022' '1032' '1012' '1052' '1062'
 '1072' '1082' '1112' '1092' '1132' '1142' '1172' '1152' '1162' '1212'
 '1222' '1232' '1272' '1262' '1252' '1332' '1302' '1292' '1662' '1632'
 '1642' '1702' '1692' '1652' '1712' '1722' '1672' '1802' '1782' '1812'
 '1772' '1792' '1822' '1842' '1852' '1832' '2722' '2702' '2712' '2752'
 '2742' '2732' '2802' '2792' '2812' '2842' '2852' '2832' '2912' '2902'
 '2932' '2942' '2952' '2922' '3802' '3812' '3782' '3872' '3852' '3832'
 '3862' '3882' '3842' '3892' '3932' '3912' '3972' '3942' '3952' '3982'
 '3992' '3962' '4042' '4032' '4002' '4112' '4092' '4082' '4122' '4152'
 '4132' '891' '911' '901' 

10840
Simulating learning for user:
652
domain:
at
N trials:
0
Simulating learning for user:
652
domain:
sb
N trials:
26
N demos:
2
N tests:
2
Failed to parse trial info again: malformed node or string: {'agent': {'x': 2, 'y': 2, 'has_skateboard': 0}, 'skateboard': [], 'goal': {'x': 6, 'y': 4}, 'walls': [], 'available_paths': [{'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 1, 'y': 4}, {'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 4, 'y': 4}], 'paths': [{'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 1, 'y': 4}, {'x': 2, 'y': 4}], 'width': 6, 'height': 4, 'gamma': 1, 'env_code': [1, 1, 1, 1, 0, 0], 'opt_locations': [[2, 2], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [6, 2], [6, 3], [6, 4]], 'opt_actions': ['down', 'right', 'right', 'right', 'right', 'up', 'up', 'up'], 'opt_traj_length': 8, 'o

Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
Parsing all data from Excel sheets...
['sb' 'at']
['652' '622' '642' '672' '632' '612' '1022' '1032' '1012' '1052' '1062'
 '1072' '1082' '1112' '1092' '1132' '1142' '1172' '1152' '1162' '1212'
 '1222' '1232' '1272' '1262' '1252' '1332' '1302' '1292' '1662' '1632'
 '1642' '1702' '1692' '1652' '1712' '1722' '1672' '1802' '1782' '1812'
 '1772' '1792' '1822' '1842' '1852' '1832' '2722' '2702' '2712' '2752'
 '2742' '2732' '2802' '2792' '2812' '2842' '2852' '2832' '2912' '2902'
 '2932' '2942' '2952' '2922' '3802' '3812' '3782' '3872' '3852' '3832'
 '3862' '3882' '3842' '3892' '3932' '3912' '3972' '3942' '3952' '3982'
 '3992' '3962' '4042' '4032' '4002' '4112' '4092' '4082' '4122' '4152'
 '4132' '891' '911' '901' '991' '1001' '981' '1011' '1021' '1031' '1111'
 '1091' '1141' '1051' '1101' '113

10840
Simulating learning for user:
652
domain:
at
N trials:
0
Simulating learning for user:
652
domain:
sb
N trials:
26
N demos:
2
N tests:
2
Failed to parse trial info again: malformed node or string: {'agent': {'x': 2, 'y': 2, 'has_skateboard': 0}, 'skateboard': [], 'goal': {'x': 6, 'y': 4}, 'walls': [], 'available_paths': [{'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 1, 'y': 4}, {'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 4, 'y': 4}], 'paths': [{'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 1, 'y': 4}, {'x': 2, 'y': 4}], 'width': 6, 'height': 4, 'gamma': 1, 'env_code': [1, 1, 1, 1, 0, 0], 'opt_locations': [[2, 2], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [6, 2], [6, 3], [6, 4]], 'opt_actions': ['down', 'right', 'right', 'right', 'right', 'up', 'up', 'up'], 'opt_traj_length': 8, 'o

['sb' 'at']
['652' '622' '642' '672' '632' '612' '1022' '1032' '1012' '1052' '1062'
 '1072' '1082' '1112' '1092' '1132' '1142' '1172' '1152' '1162' '1212'
 '1222' '1232' '1272' '1262' '1252' '1332' '1302' '1292' '1662' '1632'
 '1642' '1702' '1692' '1652' '1712' '1722' '1672' '1802' '1782' '1812'
 '1772' '1792' '1822' '1842' '1852' '1832' '2722' '2702' '2712' '2752'
 '2742' '2732' '2802' '2792' '2812' '2842' '2852' '2832' '2912' '2902'
 '2932' '2942' '2952' '2922' '3802' '3812' '3782' '3872' '3852' '3832'
 '3862' '3882' '3842' '3892' '3932' '3912' '3972' '3942' '3952' '3982'
 '3992' '3962' '4042' '4032' '4002' '4112' '4092' '4082' '4122' '4152'
 '4132' '891' '911' '901' '991' '1001' '981' '1011' '1021' '1031' '1111'
 '1091' '1141' '1051' '1101' '1131' '1161' '1071' '1121' '1081' '1171'
 '1151' '1181' '1191' '1561' '1551' '1541' '1611' '1601' '1621' '1661'
 '1631' '1651' '1701' '1681' '1671' '1761' '1751' '1741' '1801' '1781'
 '1821' '1851' '1841' '1891' '1871' '1881' '1861' '1921' '1951

[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
Reweight pf with constraint:
[[ 0 -2 -1]]
and lf:
0.8
N_particles:
2500
n_eff:
1250.0000000000055
N:
2500
N:
2500
Resampling....
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
2924
n_eff:
85.00000000000027
N:
2924
Resampling....
Reweight pf with constraint:
[[ 0 -1  0]]
and lf:
0.8
Resetting... Constraint for teacher: [[ 0 -1  0]]
N:
200
N:
200
N:
200
N:
200
N:
200
Reweight pf with constraint:
[[0 1 2]]
and lf:
0.8
Resetting... Constraint for teacher: [[0 1 2]]
N:
200
N:
200
N:
200
N:
200
N:
200
N demos:
2
N tests:
2
demo_constraints_flat:
[[[0, 1, 0]], [[0, 5, 2]], [[0, -2, -1]]]
test_constraints_flat:
[[[0, 5, 2]], array([[ 0, -3,  0]])]
feedback_constraints_flat:
[[[0, -2, -1]]]
min_demo_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_test_constraints:
[array([[ 0, -1,  0]]), array([[0, 5, 2]])]
min_feedback_constraints:
[array([[ 0, -2, -1]])]
Reweight pf with constraint:
[[ 0 -2 -1]]
and lf:
0.8
N_particles:

[[0 5 2]]
and lf:
0.8
N_particles:
179
n_eff:
135.00000000000068
N:
179
N:
179
Resampling....
N demos:
2
N tests:
2
demo_constraints_cleaned:
[]
demo_constraints_flat:
[]
test_constraints_flat:
[array([[0, 0, 2]]), array([[0, 0, 2]])]
feedback_constraints_flat:
[]
Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
Parsing all data from Excel sheets...
['sb' 'at']
['652' '622' '642' '672' '632' '612' '1022' '1032' '1012' '1052' '1062'
 '1072' '1082' '1112' '1092' '1132' '1142' '1172' '1152' '1162' '1212'
 '1222' '1232' '1272' '1262' '1252' '1332' '1302' '1292' '1662' '1632'
 '1642' '1702' '1692' '1652' '1712' '1722' '1672' '1802' '1782' '1812'
 '1772' '1792' '1822' '1842' '1852' '1832' '2722' '2702' '2712' '2752'
 '2742' '2732' '2802' '2792' '2812' '2842' '2852' '2832' '2912' '2902'
 '2932' '2942' '2952' '2922' '3802' '3812' '3782' '387

N:
192
N:
192
N demos:
2
N tests:
2
demo_constraints_flat:
[[[0, 1, 0]], [[0, 5, 2]], [[0, -2, -1]]]
test_constraints_flat:
[[[0, 5, 2]], array([[ 0, -3,  0]])]
feedback_constraints_flat:
[[[0, -2, -1]]]
min_demo_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_test_constraints:
[array([[ 0, -1,  0]]), array([[0, 5, 2]])]
min_feedback_constraints:
[array([[ 0, -2, -1]])]
min_BEC_constraints_running:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
Reweight pf with constraint:
[[ 0 -2 -1]]
and lf:
0.8
N_particles:
192
n_eff:
146.0000000000007
N:
192
N:
192
Resampling....
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
263
n_eff:
95.99999999999994
N:
263
N:
263
Resampling....
Reweight pf with constraint:
[[ 0 -1  0]]
and lf:
0.8
Resetting... Constraint for teacher: [[ 0 -1  0]]
N:
387
N:
387
N:
387
N:
387
N:
387
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
387
n_eff:
377.00000000000244
N:
387
N:
387
Resampling....
N demos:
2
N tests:
2
demo_const

and lf:
0.8
N_particles:
200
n_eff:
152.99999999999977
N:
200
Resampling....
Reweight pf with constraint:
[[ 0 -2 -1]]
and lf:
0.8
N_particles:
192
n_eff:
131.00000000000063
N:
192
N:
192
Resampling....
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
230
n_eff:
144.99999999999963
N:
230
Resampling....
N demos:
2
N tests:
2
user_id domain  round      interaction  reward_belief
0     652     sb      1             demo       0.610000
1     652     sb      1  diagnostic test       0.610000
2     652     sb      2             demo       0.663866
3     652     sb      2  diagnostic test       0.606178
4     652     sb      3             demo       0.647826
5     652     sb      3  diagnostic test       0.641026
6     652     sb      4             demo       0.442708
7     652     sb      4  diagnostic test       0.306122
Processing file: /home/sureshkj/Projects/flask_closed_loop_teaching/results/output_full_data_06_25.xlsx
File suffix: /home/sureshkj/Projects/flask_closed_loo

652
domain:
sb
N trials:
26
N demos:
2
N tests:
2
demo_constraints_flat:
[[[0, 1, 0]], [[0, 5, 2]], [[0, -2, -1]]]
test_constraints_flat:
[array([[ 0, -5,  0]]), array([[0, 1, 2]])]
feedback_constraints_flat:
[[[0, 5, 2]], [[0, -2, -1]]]
min_demo_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_test_constraints:
[array([[ 0, -1,  0]]), array([[0, 1, 2]])]
min_feedback_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_BEC_constraints_running:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
Reweight pf with constraint:
[[ 0 -2 -1]]
and lf:
0.8
N_particles:
2500
n_eff:
1250.0000000000055
N:
2500
N:
2500
Resampling....
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
2924
n_eff:
94.00000000000024
N:
2924
Resampling....
Reweight pf with constraint:
[[ 0 -1  0]]
and lf:
0.8
Resetting... Constraint for teacher: [[ 0 -1  0]]
N:
192
N:
192
N:
192
N:
192
N:
192
Reweight pf with constraint:
[[0 1 2]]
and lf:
0.8
N_particles:
192
n_eff:
2.0
N:
192
Resampling....
N

10840
Simulating learning for user:
652
domain:
at
N trials:
0
Simulating learning for user:
652
domain:
sb
N trials:
26
N demos:
2
N tests:
2
demo_constraints_flat:
[[[0, 1, 0]], [[0, 5, 2]], [[0, -2, -1]]]
test_constraints_flat:
[array([[ 0, -5,  0]]), array([[0, 1, 2]])]
feedback_constraints_flat:
[[[0, 5, 2]], [[0, -2, -1]]]
min_demo_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_test_constraints:
[array([[ 0, -1,  0]]), array([[0, 1, 2]])]
min_feedback_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_BEC_constraints_running:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
Reweight pf with constraint:
[[ 0 -2 -1]]
and lf:
0.8
N_particles:
2500
n_eff:
1250.0000000000055
N:
2500
N:
2500
Resampling....
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
2924
n_eff:
85.00000000000027
N:
2924
Resampling....
Reweight pf with constraint:
[[ 0 -1  0]]
and lf:
0.8
Resetting... Constraint for teacher: [[ 0 -1  0]]
N:
187
N:
187
N:
187
N:
187
N:
187
Reweight 

min_feedback_constraints:
[array([[ 0, -2, -1]])]
min_BEC_constraints_running:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
Reweight pf with constraint:
[[ 0 -2 -1]]
and lf:
0.8
N_particles:
183
n_eff:
170.0000000000007
N:
183
N:
183
Resampling....
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
183
n_eff:
178.00000000000077
N:
183
N:
183
Resampling....
Reweight pf with constraint:
[[ 0 -1  0]]
and lf:
0.8
Resetting... Constraint for teacher: [[ 0 -1  0]]
N:
187
N:
187
N:
187
N:
187
N:
187
Reweight pf with constraint:
[[0 5 2]]
and lf:
0.8
N_particles:
187
n_eff:
185.00000000000117
N:
187
N:
187
Resampling....
N demos:
2
N tests:
2
demo_constraints_flat:
[[[0, 1, 0]], [[0, 5, 2]], [[0, -2, -1]]]
test_constraints_flat:
[[[0, 5, 2]], [[0, -2, -1]]]
feedback_constraints_flat:
[]
min_demo_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_test_constraints:
[array([[ 0, -2, -1]]), array([[0, 5, 2]])]
min_feedback_constraints:
[array([[ 0, -2, -1]])]
min_BEC_constrai

In [61]:
# Functions to get constraints

domain_map = {
    'at': 'augmented_taxi2',
    'sb': 'skateboard2'
}

def parse_trial_mdp_info(domain, trial_str):
    """
    Parses trial MDP information from a string, extracting environment index,
    optimal moves, and the parsed MDP dictionary.

    Args:
        domain (str): The domain ('at' or 'sb').
        trial_str (str): A string representation of the trial MDP dictionary.

    Returns:
        tuple: (env_idx, opt_moves, trial_mdp_dict). env_idx can be None.
    """
    if domain == 'at':
        mdp_class = 'augmented_taxi2'
    elif domain == 'sb':
        mdp_class = 'skateboard2'
    else:
        raise ValueError(f"Unknown domain: {domain}")

    try:
        trial_mdp_dict = ast.literal_eval(trial_str)
        env_idx = trial_mdp_dict.get('env_traj_idxs', [None])[0]
        opt_moves = trial_mdp_dict.get('opt_actions', [])
        return env_idx, opt_moves, trial_mdp_dict
    except (ValueError, SyntaxError) as e:
        print(f"Warning: Could not parse trial_str '{trial_str}'. Attempting fallback. Error: {e}")
        # Fallback if direct parsing fails, try to find an environment file
        # This part of the original logic seems a bit ambiguous.
        # If the `trial_str` is truly malformed, `ast.literal_eval` will fail again.
        # Re-evaluating `trial_str` within the except block is redundant if it failed once.
        # The original code's commented out section suggests attempting `check_env_files` here,
        # but it was commented out. For clarity, I'll keep the current behavior but note the ambiguity.
        # If `check_env_files` is truly intended as a fallback for missing `env_traj_idxs`,
        # it should be called after successful `ast.literal_eval` but before the return.

        # If trial_str is truly unparseable as a dict, this will likely fail again.
        # Consider a more robust parsing or simply returning defaults if it's consistently malformed.
        try:
            trial_mdp_dict = ast.literal_eval(trial_str)
            opt_moves = trial_mdp_dict.get('opt_actions', [])
            env_idx = check_env_files(mdp_class, trial_mdp_dict) # Call the helper function
            return env_idx, opt_moves, trial_mdp_dict
        except (ValueError, SyntaxError) as e:
            print(f"Failed to parse trial info again: {e}")
            return None, [], {} # Return safe defaults if parsing completely fails


def get_traj_from_mdp(mdp, current_state, moves_list, weights=None):
    """
    Generates a trajectory by executing a sequence of moves in an MDP.

    Args:
        mdp (object): The MDP object.
        current_state (object): The initial state.
        moves_list (list): A list of actions to execute.
        weights (np.ndarray, optional): Reward weights to set on the MDP. Defaults to None.

    Returns:
        list: The generated trajectory, a list of (state, action, next_state) tuples.
    """
    if weights is not None:
        mdp.weights = weights

    trajectory = []
    for move in moves_list:
        # Assumes that the user study only allows actions that change the state of the MDP
        # and that mdp.execute_agent_action updates the internal state of mdp.
        reward, next_state = mdp.execute_agent_action(move)
        trajectory.append((current_state, move, next_state))
        current_state = next_state # Update current_state for the next iteration

    return trajectory


def calculate_incorrect_constraints(domain, mdp_parameters, moves):
    
    sb_gt_weights = np.array([[0.59565914, 0.3519804, -0.72201107]])
    at_gt_weights = np.array([[-0.63599873, 0.74199852, -0.21199958]])

    if domain == 'at':
        gt_weights = at_gt_weights
    elif domain == 'sb':
        gt_weights = sb_gt_weights
    else:
        # Handle cases where domain is not 'at' or 'sb'
        print(f"Warning: Unknown domain '{domain}'. Cannot check reward sign correctness.")
        return False

    # Parse trial MDP info and moves
    env_idx, opt_moves, trial_mdp_dict = parse_trial_mdp_info(domain, mdp_parameters)
    human_moves = ast.literal_eval(moves)
    # human_est_weights = normalize_reward_weights(trial_data['reward_ft_weights']) # Not used in final return, so commented out

    # Make custom MDP (assuming make_custom_mdp handles different classes)
    trial_mdp_dict['weights'] = gt_weights # Set weights for MDP creation
    mdp = make_custom_mdp(domain_map.get(domain), trial_mdp_dict) # Use a clearer domain map

    current_state = mdp.get_init_state()

    # Get optimal and human trajectories under ground truth MDP
    opt_traj = get_traj_from_mdp(mdp, current_state, opt_moves, weights=gt_weights)
    mdp.reset() # Reset MDP state for the next trajectory calculation
    human_traj = get_traj_from_mdp(mdp, current_state, human_moves, weights=gt_weights)
    mdp.reset()

    # Feature counts
    phi_opt = mdp.accumulate_reward_features(opt_traj, discount=True)
    mdp.reset()
    phi_human = mdp.accumulate_reward_features(human_traj, discount=True)
    mdp.reset()
    
    # opt-human is the difference or gap in knowledge, so its inverse is the actual knowledge
    return phi_human - phi_opt


In [34]:
def _standardize_id_column(df, column_name):
    """
    Helper function to standardize ID columns: fill NaNs, convert to int then str,
    and replace '-1' with an empty string.

    Args:
        df (pd.DataFrame): The DataFrame to modify.
        column_name (str): The name of the column to standardize.

    Returns:
        pd.DataFrame: The DataFrame with the standardized column.
    """
    # Ensure a copy to avoid SettingWithCopyWarning
    df_copy = df.copy()
    df_copy[column_name] = df_copy[column_name].fillna(-1).astype(int).astype(str)
    df_copy.loc[df_copy[column_name] == '-1', column_name] = ''
    return df_copy

def _flatten_one_more_level(nested_list):
    """Flattens a list of lists one level deeper if sub-elements are also lists."""
    flattened = []
    for item in nested_list:
        if isinstance(item, list) and all(isinstance(sub, list) for sub in item):
            flattened.extend(item)
        else:
            flattened.append(item)
    return flattened


def _is_valid_constraint(c):
    """Checks if a constraint list is valid (not None or empty/all None)."""
    if c is None:
        return False
    # Flatten and check if any element is not None
    flat_list = []
    for item in c:
        if isinstance(item, list):
            for sub_item in item:
                flat_list.append(sub_item)
        else:
            flat_list.append(item)
    return any(x is not None for x in flat_list)

## Run learning loop

In [65]:

filename = os.path.abspath('../results/output_full_data_06_25.xlsx')
print(f'Processing file: {filename}')

# Determine file suffix for output naming
file_suffix = filename[len('output_'):] if filename.startswith('output_') else filename
print(f'File suffix: {file_suffix}')

# Read all sheets from the Excel file
excel_file = pd.ExcelFile(filename)
print('Parsing all data from Excel sheets...', flush=True)

# --- Load and Clean DataFrames ---
user_df = excel_file.parse('user')
user_df = _standardize_id_column(user_df, 'group')
user_df = _standardize_id_column(user_df, 'id')

trial_df = excel_file.parse('trial')
trial_df['group_id'] = trial_df['group'].copy() # Create 'group_id' from 'group'
trial_df = _standardize_id_column(trial_df, 'group')
trial_df = _standardize_id_column(trial_df, 'user_id')
trial_df = trial_df.drop_duplicates(subset=['user_id', 'group', 'domain', 'round', 'iteration'])


################

# Group by user
users = trial_df['user_id'].unique()

user_knowledge_df = pd.DataFrame()

print(trial_df['domain'].unique())
print(trial_df['user_id'].unique())

print(len(trial_df))

# Main PF update loop
for user in users:
    
    user_knowledge_dict = {}
    
    for domain in ['at', 'sb']:
        if domain == 'at':
            mdp_class = 'augmented_taxi2'
        elif domain == 'sb':
            mdp_class = 'skateboard2'
        params = get_mdp_parameters(mdp_class)
        params['teacher_update_model_type'] = 'low_noise'
        
        n_particles = 2500
        N_elevation_bins = params['N_elevation_bins']
        step_cost_flag = params['step_cost_flag']
        weights = params['mdp_parameters']['weights']
        teaching_uf = params['teacher_learning_factor']
        model_type = params['teacher_update_model_type']
        
        user_pf = pf_team.Particles_team(sample_human_models_uniform([], n_particles), teaching_uf, N_elevation_bins)
        
        print('Simulating learning for user: ', user, 'domain:', domain)
        
        # user-domain trial data
        user_trial_data = trial_df[(trial_df['user_id']==user) & (trial_df['domain']==domain)]
        
        print('N trials: ', len(user_trial_data))
        
        min_BEC_constraints_running = []

        if len(user_trial_data) > 0:
        
            N_lessons = user_trial_data[user_trial_data['interaction_type']=='diagnostic test'].iloc[-1]['round']

            for lesson in range(1, N_lessons+1):

                demos = user_trial_data[(user_trial_data['interaction_type']=='demo') & (user_trial_data['round']==lesson)]
                tests = user_trial_data[(user_trial_data['interaction_type']=='diagnostic test') & (user_trial_data['round']==lesson)]
                
                print('N demos:', len(demos))
                print('N tests:', len(tests))
                
                demo_constraints = []
                
                for _, demo in demos.iterrows():
                    env_idx, opt_moves, trial_mdp_dict = parse_trial_mdp_info(domain, demo['mdp_parameters'])
                    demo_constraints.append(trial_mdp_dict.get('constraints', []))
                
                demo_constraints_cleaned = [c for c in demo_constraints if _is_valid_constraint(c)]
                demo_constraints_flat = _flatten_one_more_level(demo_constraints_cleaned) if demo_constraints_cleaned else []
                
                test_constraints = []
                feedback_constraints = []
                
                for _, test in tests.iterrows():
                    env_idx, opt_moves, trial_mdp_dict = parse_trial_mdp_info(domain, test['mdp_parameters'])
                    
                    if test['is_opt_response']==1:    
                        test_constraints.append(trial_mdp_dict.get('constraints', []))
                    else:
                        test_constraints.append(calculate_incorrect_constraints(domain, test['mdp_parameters'], test['moves']))
                        feedback_constraints.append(trial_mdp_dict.get('constraints', []))
                        
                test_constraints_cleaned = [c for c in test_constraints if _is_valid_constraint(c)]
                test_constraints_flat = _flatten_one_more_level(test_constraints_cleaned) if test_constraints_cleaned else []
                
                
                if len(demo_constraints_flat) > 0:

                    feedback_constraints_cleaned = [c for c in feedback_constraints if _is_valid_constraint(c)]
                    feedback_constraints_flat = _flatten_one_more_level(feedback_constraints_cleaned) if feedback_constraints_cleaned else []

                    print('demo_constraints_flat: ', demo_constraints_flat)
                    print('test_constraints_flat: ', test_constraints_flat)
                    print('feedback_constraints_flat: ', feedback_constraints_flat)

                    min_demo_constraints = remove_redundant_constraints(demo_constraints_flat, weights, step_cost_flag) # minimum constraints conveyed by the unit's demonstrations
                    min_test_constraints = remove_redundant_constraints(test_constraints_flat, weights, step_cost_flag) # minimum constraints conveyed by the unit's demonstrations

                    if feedback_constraints_flat:
                        min_feedback_constraints = remove_redundant_constraints(feedback_constraints_flat, weights, step_cost_flag)

                    print('min_demo_constraints: ', min_demo_constraints)
                    print('min_test_constraints: ', min_test_constraints)
                    print('min_feedback_constraints: ', min_feedback_constraints)

                    min_BEC_constraints_running.extend(min_demo_constraints)
                    min_BEC_constraints_running = remove_redundant_constraints(min_BEC_constraints_running, weights, step_cost_flag)
                    
                    print('min_BEC_constraints_running: ', min_BEC_constraints_running)
                    
                    # Update the particle filter - demos
                    user_pf.update(min_demo_constraints, teaching_uf, model_type, params)
                    user_pf.calc_particles_probability(min_BEC_constraints_running, true_reward_weights=params['mdp_parameters']['weights'])

                    user_knowledge_dict = {'user_id': user, 'domain': domain, 'round': lesson, 'interaction': 'demo', 'reward_belief': user_pf.particles_prob_correct}
                    user_knowledge_df = user_knowledge_df.append(user_knowledge_dict, ignore_index=True)

                    # Update the particle filter - tests
                    user_pf.update(min_test_constraints, teaching_uf, model_type, params)
                    user_pf.calc_particles_probability(min_BEC_constraints_running, true_reward_weights=params['mdp_parameters']['weights'])

                    user_knowledge_dict = {'user_id': user, 'domain': domain, 'round': lesson, 'interaction': 'diagnostic test', 'reward_belief': user_pf.particles_prob_correct}
                    user_knowledge_df = user_knowledge_df.append(user_knowledge_dict, ignore_index=True)

    break

print(user_knowledge_df)
